//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADRetrieveUserAttributesProject
{
    using System;
    using HP.ST.Fwk.RunTimeFWK;
    
    
    public partial class ADRetrieveUserAttributes
    {
        
        private string _samaaccountname;
        
        private string _ldap;
        
        private string _adcredentialusername;
        
        private string _adcredentialpassword;
        
        private string _firstname;
        
        private string _lastname;
        
        private string _displayname;
        
        private string _commonname;
        
        private string _initial;
        
        private string _employeeid;
        
        private string _employeetype;
        
        private string _employeenumber;
        
        private string _gender;
        
        private string _location;
        
        private string _address;
        
        private string _city;
        
        private string _zip_postalcode;
        
        private string _state;
        
        private string _country;
        
        private string _countryisocode;
        
        private string _userlogonname;
        
        private string _jobtitle;
        
        private string _department;
        
        private string _division;
        
        private string _company;
        
        private string _manager;
        
        private string _email;
        
        private string _description;
        
        private string _departmentnumber;
        
        private string _groups;
        
        private string _name;
        
        //  InputProperties Section
        [Report()]
        public virtual string sAMAaccountName
        {
            get
            {
                return this._samaaccountname;
            }
            set
            {
                this._samaaccountname = value;
            }
        }
        
        [Report()]
        public virtual string LDAP
        {
            get
            {
                return this._ldap;
            }
            set
            {
                this._ldap = value;
            }
        }
        
        [Report()]
        public virtual string ADCredentialUserName
        {
            get
            {
                return this._adcredentialusername;
            }
            set
            {
                this._adcredentialusername = value;
            }
        }
        
        [Report()]
        public virtual string ADCredentialPassword
        {
            get
            {
                return this._adcredentialpassword;
            }
            set
            {
                this._adcredentialpassword = value;
            }
        }
        
        //  OutputProperties Section
        [Report()]
        public virtual string FirstName
        {
            get
            {
                return this._firstname;
            }
            set
            {
                this._firstname = value;
            }
        }
        
        [Report()]
        public virtual string LastName
        {
            get
            {
                return this._lastname;
            }
            set
            {
                this._lastname = value;
            }
        }
        
        [Report()]
        public virtual string DisplayName
        {
            get
            {
                return this._displayname;
            }
            set
            {
                this._displayname = value;
            }
        }
        
        [Report()]
        public virtual string CommonName
        {
            get
            {
                return this._commonname;
            }
            set
            {
                this._commonname = value;
            }
        }
        
        [Report()]
        public virtual string Initial
        {
            get
            {
                return this._initial;
            }
            set
            {
                this._initial = value;
            }
        }
        
        [Report()]
        public virtual string EmployeeID
        {
            get
            {
                return this._employeeid;
            }
            set
            {
                this._employeeid = value;
            }
        }
        
        [Report()]
        public virtual string EmployeeType
        {
            get
            {
                return this._employeetype;
            }
            set
            {
                this._employeetype = value;
            }
        }
        
        [Report()]
        public virtual string EmployeeNumber
        {
            get
            {
                return this._employeenumber;
            }
            set
            {
                this._employeenumber = value;
            }
        }
        
        [Report()]
        public virtual string Gender
        {
            get
            {
                return this._gender;
            }
            set
            {
                this._gender = value;
            }
        }
        
        [Report()]
        public virtual string Location
        {
            get
            {
                return this._location;
            }
            set
            {
                this._location = value;
            }
        }
        
        [Report()]
        public virtual string Address
        {
            get
            {
                return this._address;
            }
            set
            {
                this._address = value;
            }
        }
        
        [Report()]
        public virtual string City
        {
            get
            {
                return this._city;
            }
            set
            {
                this._city = value;
            }
        }
        
        [Report()]
        public virtual string ZIP_PostalCode
        {
            get
            {
                return this._zip_postalcode;
            }
            set
            {
                this._zip_postalcode = value;
            }
        }
        
        [Report()]
        public virtual string State
        {
            get
            {
                return this._state;
            }
            set
            {
                this._state = value;
            }
        }
        
        [Report()]
        public virtual string Country
        {
            get
            {
                return this._country;
            }
            set
            {
                this._country = value;
            }
        }
        
        [Report()]
        public virtual string CountryISOcode
        {
            get
            {
                return this._countryisocode;
            }
            set
            {
                this._countryisocode = value;
            }
        }
        
        [Report()]
        public virtual string UserLogonName
        {
            get
            {
                return this._userlogonname;
            }
            set
            {
                this._userlogonname = value;
            }
        }
        
        [Report()]
        public virtual string JobTitle
        {
            get
            {
                return this._jobtitle;
            }
            set
            {
                this._jobtitle = value;
            }
        }
        
        [Report()]
        public virtual string Department
        {
            get
            {
                return this._department;
            }
            set
            {
                this._department = value;
            }
        }
        
        [Report()]
        public virtual string Division
        {
            get
            {
                return this._division;
            }
            set
            {
                this._division = value;
            }
        }
        
        [Report()]
        public virtual string Company
        {
            get
            {
                return this._company;
            }
            set
            {
                this._company = value;
            }
        }
        
        [Report()]
        public virtual string Manager
        {
            get
            {
                return this._manager;
            }
            set
            {
                this._manager = value;
            }
        }
        
        [Report()]
        public virtual string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                this._email = value;
            }
        }
        
        [Report()]
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        
        [Report()]
        public virtual string DepartmentNumber
        {
            get
            {
                return this._departmentnumber;
            }
            set
            {
                this._departmentnumber = value;
            }
        }
        
        [Report()]
        public virtual string Groups
        {
            get
            {
                return this._groups;
            }
            set
            {
                this._groups = value;
            }
        }
        
        //  GeneralProperties Section
        [Report()]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
}
